# 📊 Data Analysis Notebook

This notebook performs **Exploratory Data Analysis (EDA)** on the cleaned car sales data.

**Datasets:**
- `Cars_cleaned.csv` - Car inventory data
- `Customers_cleaned.csv` - Customer information
- `Sales_cleaned.csv` - Sales transaction records

## 1. Imports and Setup

In [1]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sys
import os

# Add project root to path to allow importing src
from pathlib import Path

project_root = Path(os.getcwd())
while not (project_root / ".git").exists() and project_root != project_root.parent:
    project_root = project_root.parent
sys.path.append(str(project_root))

# IMPORT NEW DATA MANAGER
from src.utils.data_manager import load_from, save_to, save_result, ChartConfig

# Set styles
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)
plt.rcParams["font.size"] = 12

# Premium color palette
COLORS = ["#4c72b0", "#55a868", "#c44e52", "#8172b2", "#ccb974", "#64b5cd"]
px.defaults.color_discrete_sequence = COLORS

print("✅ Libraries and Helper Functions loaded successfully!")

✅ Libraries and Helper Functions loaded successfully!

## 2. Load Data

In [2]:
# Load datasets using helper functions
df_cars = pl.read_csv(load_from("cleaned", "Cars_cleaned.csv"))
df_customers = pl.read_csv(load_from("cleaned", "Customers_cleaned.csv"))
df_sales = pl.read_csv(load_from("cleaned", "Sales_cleaned.csv"))

print(f"🚗 Cars: {df_cars.shape[0]:,} rows, {df_cars.shape[1]} columns")
print(f"👤 Customers: {df_customers.shape[0]:,} rows, {df_customers.shape[1]} columns")
print(f"💰 Sales: {df_sales.shape[0]:,} rows, {df_sales.shape[1]} columns")

🚗 Cars: 49,489 rows, 10 columns
👤 Customers: 500 rows, 11 columns
💰 Sales: 49,988 rows, 8 columns

In [3]:
# Preview Cars data
print("=== Cars Dataset ===")
print(df_cars.schema)
df_cars.head()

=== Cars Dataset ===
Schema({'Brand': String, 'Model': String, 'Year': Int64, 'Price': Float64, 'Car_ID': String, 'Color': String, 'Engine_Type': String, 'Transmission': String, 'Quantity_In_Stock': Int64, 'Status': String})

shape: (5, 10)
┌────────┬───────┬──────┬─────────┬───┬─────────────┬──────────────┬───────────────────┬───────────┐
│ Brand  ┆ Model ┆ Year ┆ Price   ┆ … ┆ Engine_Type ┆ Transmission ┆ Quantity_In_Stock ┆ Status    │
│ ---    ┆ ---   ┆ ---  ┆ ---     ┆   ┆ ---         ┆ ---          ┆ ---               ┆ ---       │
│ str    ┆ str   ┆ i64  ┆ f64     ┆   ┆ str         ┆ str          ┆ i64               ┆ str       │
╞════════╪═══════╪══════╪═════════╪═══╪═════════════╪══════════════╪═══════════════════╪═══════════╡
│ Toyota ┆ RAV4  ┆ 1993 ┆ 3469.0  ┆ … ┆ Petrol      ┆ Automatic    ┆ 10                ┆ Available │
│ Bmw    ┆ Z4    ┆ 1989 ┆ 1539.0  ┆ … ┆ Petrol      ┆ Automatic    ┆ 10                ┆ Available │
│ Toyota ┆ RAV4  ┆ 1998 ┆ 9396.0  ┆ … ┆ Petrol      ┆ Automatic    ┆ 10                ┆ Available │
│ Bmw    ┆ X3    ┆ 2011 ┆ 24295.0 ┆ … ┆ Petrol      ┆ Automatic    ┆ 10                ┆ Available │
│ Bmw    ┆ Z4    ┆ 2009 ┆ 11572.0 ┆ … ┆ Petrol      ┆ Automatic    ┆ 10                ┆ Available │
└────────┴───────┴──────┴─────────┴───┴─────────────┴──────────────┴───────────────────┴───────────┘

In [4]:
# Preview Customers data
print("=== Customers Dataset ===")
print(df_customers.schema)
df_customers.head()

=== Customers Dataset ===
Schema({'Customer_ID': String, 'First Name': String, 'Last Name': Int64, 'Gender': String, 'Age': Int64, 'Job Role': String, 'Phone': String, 'Email': String, 'City': String, 'State': String, 'Region': String})

shape: (5, 11)
┌─────────────┬────────────┬───────────┬────────┬───┬───────────────┬─────────┬──────────┬─────────┐
│ Customer_ID ┆ First Name ┆ Last Name ┆ Gender ┆ … ┆ Email         ┆ City    ┆ State    ┆ Region  │
│ ---         ┆ ---        ┆ ---       ┆ ---    ┆   ┆ ---           ┆ ---     ┆ ---      ┆ ---     │
│ str         ┆ str        ┆ i64       ┆ str    ┆   ┆ str           ┆ str     ┆ str      ┆ str     │
╞═════════════╪════════════╪═══════════╪════════╪═══╪═══════════════╪═════════╪══════════╪═════════╡
│ CU0001      ┆ Customer   ┆ 1         ┆ Other  ┆ … ┆ user1@example ┆ Bangkok ┆ Thailand ┆ East    │
│             ┆            ┆           ┆        ┆   ┆ .com          ┆         ┆          ┆         │
│ CU0002      ┆ Customer   ┆ 2         ┆ Other  ┆ … ┆ user2@example ┆ Bangkok ┆ Thailand ┆ Central │
│             ┆            ┆           ┆        ┆   ┆ .com          ┆         ┆          ┆         │
│ CU0003      ┆ Customer   ┆ 3         ┆ Other  ┆ … ┆ user3@example ┆ Bangkok ┆ Thailand ┆ South   │
│             ┆            ┆           ┆        ┆   ┆ .com          ┆         ┆          ┆         │
│ CU0004      ┆ Customer   ┆ 4         ┆ Other  ┆ … ┆ user4@example ┆ Bangkok ┆ Thailand ┆ West    │
│             ┆            ┆           ┆        ┆   ┆ .com          ┆         ┆          ┆         │
│ CU0005      ┆ Customer   ┆ 5         ┆ Other  ┆ … ┆ user5@example ┆ Bangkok ┆ Thailand ┆ South   │
│             ┆            ┆           ┆        ┆   ┆ .com          ┆         ┆          ┆         │
└─────────────┴────────────┴───────────┴────────┴───┴───────────────┴─────────┴──────────┴─────────┘

In [5]:
# Preview Sales data
print("=== Sales Dataset ===")
print(df_sales.schema)
df_sales.head()

=== Sales Dataset ===
Schema({'Sale_ID': String, 'Customer_ID': String, 'Car_ID': String, 'Sale_Date': String, 'Quantity': Int64, 'Sale_Price': Float64, 'Payment_Method': String, 'Salesperson': String})

shape: (5, 8)
┌─────────┬─────────────┬────────┬────────────┬──────────┬────────────┬──────────────┬─────────────┐
│ Sale_ID ┆ Customer_ID ┆ Car_ID ┆ Sale_Date  ┆ Quantity ┆ Sale_Price ┆ Payment_Meth ┆ Salesperson │
│ ---     ┆ ---         ┆ ---    ┆ ---        ┆ ---      ┆ ---        ┆ od           ┆ ---         │
│ str     ┆ str         ┆ str    ┆ str        ┆ i64      ┆ f64        ┆ ---          ┆ str         │
│         ┆             ┆        ┆            ┆          ┆            ┆ str          ┆             │
╞═════════╪═════════════╪════════╪════════════╪══════════╪════════════╪══════════════╪═════════════╡
│ S00001  ┆ CU0138      ┆ C16838 ┆ 2024-01-01 ┆ 1        ┆ 6759.0     ┆ Cash         ┆ AI Bot      │
│ S00002  ┆ CU0372      ┆ C48954 ┆ 2024-01-01 ┆ 1        ┆ 51340.0    ┆ Cash         ┆ AI Bot      │
│ S00003  ┆ CU0315      ┆ C10539 ┆ 2024-01-01 ┆ 1        ┆ 39148.0    ┆ Cash         ┆ AI Bot      │
│ S00004  ┆ CU0371      ┆ C20414 ┆ 2024-01-01 ┆ 1        ┆ 31489.0    ┆ Cash         ┆ AI Bot      │
│ S00005  ┆ CU0492      ┆ C4675  ┆ 2024-01-01 ┆ 1        ┆ 5310.0     ┆ Cash         ┆ AI Bot      │
└─────────┴─────────────┴────────┴────────────┴──────────┴────────────┴──────────────┴─────────────┘

## 3. Data Merging

In [6]:
# Join Sales with Cars on Car_ID
df_master = df_sales.join(df_cars, on="Car_ID", how="left")

# Join with Customers on Customer_ID
df_master = df_master.join(df_customers, on="Customer_ID", how="left")

print(f"📊 Master Dataset: {df_master.shape[0]:,} rows, {df_master.shape[1]} columns")
print(f"\nColumns: {df_master.columns}")

📊 Master Dataset: 49,988 rows, 27 columns

Columns: ['Sale_ID', 'Customer_ID', 'Car_ID', 'Sale_Date', 'Quantity', 'Sale_Price', 'Payment_Method', 'Salesperson', 'Brand', 'Model', 'Year', 'Price', 'Color', 'Engine_Type', 'Transmission', 'Quantity_In_Stock', 'Status', 'First Name', 'Last Name', 'Gender', 'Age', 'Job Role', 'Phone', 'Email', 'City', 'State', 'Region']

In [7]:
# Preview master dataset
df_master.head()

shape: (5, 27)
┌─────────┬─────────────┬────────┬────────────┬───┬─────────────────┬─────────┬──────────┬─────────┐
│ Sale_ID ┆ Customer_ID ┆ Car_ID ┆ Sale_Date  ┆ … ┆ Email           ┆ City    ┆ State    ┆ Region  │
│ ---     ┆ ---         ┆ ---    ┆ ---        ┆   ┆ ---             ┆ ---     ┆ ---      ┆ ---     │
│ str     ┆ str         ┆ str    ┆ str        ┆   ┆ str             ┆ str     ┆ str      ┆ str     │
╞═════════╪═════════════╪════════╪════════════╪═══╪═════════════════╪═════════╪══════════╪═════════╡
│ S00001  ┆ CU0138      ┆ C16838 ┆ 2024-01-01 ┆ … ┆ user138@example ┆ Bangkok ┆ Thailand ┆ West    │
│         ┆             ┆        ┆            ┆   ┆ .com            ┆         ┆          ┆         │
│ S00002  ┆ CU0372      ┆ C48954 ┆ 2024-01-01 ┆ … ┆ user372@example ┆ Bangkok ┆ Thailand ┆ Central │
│         ┆             ┆        ┆            ┆   ┆ .com            ┆         ┆          ┆         │
│ S00003  ┆ CU0315      ┆ C10539 ┆ 2024-01-01 ┆ … ┆ user315@example ┆ Bangkok ┆ Thailand ┆ North   │
│         ┆             ┆        ┆            ┆   ┆ .com            ┆         ┆          ┆         │
│ S00004  ┆ CU0371      ┆ C20414 ┆ 2024-01-01 ┆ … ┆ user371@example ┆ Bangkok ┆ Thailand ┆ West    │
│         ┆             ┆        ┆            ┆   ┆ .com            ┆         ┆          ┆         │
│ S00005  ┆ CU0492      ┆ C4675  ┆ 2024-01-01 ┆ … ┆ user492@example ┆ Bangkok ┆ Thailand ┆ East    │
│         ┆             ┆        ┆            ┆   ┆ .com            ┆         ┆          ┆         │
└─────────┴─────────────┴────────┴────────────┴───┴─────────────────┴─────────┴──────────┴─────────┘

---
## 4. Exploratory Data Analysis (EDA)

### 4.1 Univariate Analysis

#### 4.1.1 Numerical Distributions

In [8]:
# Price Distribution (Cars)
fig = px.histogram(
    df_cars.to_pandas(),
    x="Price",
    nbins=50,
    title="🚗 Car Price Distribution",
    labels={"Price": "Price ($)", "count": "Frequency"},
    color_discrete_sequence=[COLORS[0]],
)
fig.update_layout(bargap=0.1)
fig.show()

In [9]:
# Age Distribution (Customers)
fig = px.histogram(
    df_customers.to_pandas(),
    x="Age",
    nbins=30,
    title="👤 Customer Age Distribution",
    labels={"Age": "Age (years)", "count": "Frequency"},
    color_discrete_sequence=[COLORS[2]],
)
fig.show()

#### 4.1.2 Categorical Frequencies

In [10]:
# Top 10 Brands
brand_counts = (
    df_cars.group_by("Brand")
    .agg(pl.len().alias("Count"))
    .sort("Count", descending=True)
    .head(10)
)

fig = px.bar(
    brand_counts.to_pandas(),
    x="Brand",
    y="Count",
    title="🏷️ Top Car Brands (by Inventory Count)",
    color="Brand",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False)
fig.show()

In [11]:
# Top 10 Models
model_counts = (
    df_cars.group_by("Model")
    .agg(pl.len().alias("Count"))
    .sort("Count", descending=True)
    .head(10)
)

fig = px.bar(
    model_counts.to_pandas(),
    x="Model",
    y="Count",
    title="🚘 Top 10 Car Models (by Inventory Count)",
    color="Model",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False)
fig.show()

In [12]:
# Engine Type Distribution
engine_counts = (
    df_cars.group_by("Engine_Type")
    .agg(pl.len().alias("Count"))
    .sort("Count", descending=True)
)

fig = px.pie(
    engine_counts.to_pandas(),
    values="Count",
    names="Engine_Type",
    title="⚙️ Engine Type Distribution",
    color_discrete_sequence=COLORS,
    hole=0.4,
)
fig.show()

In [13]:
# Transmission Distribution
trans_counts = (
    df_cars.group_by("Transmission")
    .agg(pl.len().alias("Count"))
    .sort("Count", descending=True)
)

fig = px.pie(
    trans_counts.to_pandas(),
    values="Count",
    names="Transmission",
    title="🔧 Transmission Type Distribution",
    color_discrete_sequence=COLORS,
    hole=0.4,
)
fig.show()

In [14]:
# Region Distribution (Customers)
region_counts = (
    df_customers.group_by("Region")
    .agg(pl.len().alias("Count"))
    .sort("Count", descending=True)
)

fig = px.bar(
    region_counts.to_pandas(),
    x="Region",
    y="Count",
    title="🗺️ Customer Distribution by Region",
    color="Region",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False)
fig.show()

In [15]:
# Payment Method Distribution (Sales)
payment_counts = (
    df_sales.group_by("Payment_Method")
    .agg(pl.len().alias("Count"))
    .sort("Count", descending=True)
)

fig = px.pie(
    payment_counts.to_pandas(),
    values="Count",
    names="Payment_Method",
    title="💳 Payment Method Distribution",
    color_discrete_sequence=COLORS,
    hole=0.4,
)
fig.show()

#### 4.1.3 Outlier Detection

In [16]:
# Box plots for Price and Quantity
fig = make_subplots(rows=1, cols=2, subplot_titles=("Car Price", "Sale Quantity"))

fig.add_trace(
    go.Box(y=df_cars["Price"].to_list(), name="Price", marker_color=COLORS[0]),
    row=1,
    col=1,
)

fig.add_trace(
    go.Box(y=df_sales["Quantity"].to_list(), name="Quantity", marker_color=COLORS[1]),
    row=1,
    col=2,
)

fig.update_layout(title_text="📦 Outlier Detection - Box Plots", showlegend=False)
fig.show()

---
### 4.2 Bivariate & Multivariate Analysis

#### 4.2.1 Correlation Analysis

In [17]:
# Select numerical columns for correlation
numerical_cols = ["Price", "Year", "Quantity_In_Stock", "Quantity", "Sale_Price", "Age"]

# Filter columns that exist in master dataset
available_cols = [col for col in numerical_cols if col in df_master.columns]

# Convert to pandas for correlation matrix
corr_df = df_master.select(available_cols).to_pandas()
corr_matrix = corr_df.corr()

# Heatmap
fig = px.imshow(
    corr_matrix,
    text_auto=".2f",
    title="🔥 Correlation Heatmap",
    color_continuous_scale="RdBu_r",
    zmin=-1,
    zmax=1,
)
fig.show()

#### 4.2.2 Sales Performance by Category

In [18]:
# Average Price per Brand
avg_price_brand = (
    df_master.group_by("Brand")
    .agg(pl.mean("Price").alias("Avg_Price"))
    .sort("Avg_Price", descending=True)
)

fig = px.bar(
    avg_price_brand.to_pandas(),
    x="Brand",
    y="Avg_Price",
    title="💰 Average Car Price by Brand",
    color="Brand",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False, yaxis_title="Average Price ($)")
fig.show()

In [19]:
# Average Price per Engine Type
avg_price_engine = (
    df_master.group_by("Engine_Type")
    .agg(pl.mean("Sale_Price").alias("Avg_Sale_Price"))
    .sort("Avg_Sale_Price", descending=True)
)

fig = px.bar(
    avg_price_engine.to_pandas(),
    x="Engine_Type",
    y="Avg_Sale_Price",
    title="⚙️ Average Sale Price by Engine Type",
    color="Engine_Type",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False, yaxis_title="Average Sale Price ($)")
fig.show()

In [20]:
# --- 1. Data Aggregation ---
# Group by car model to get the required metrics
model_sales_summary = (
    df_master.group_by("Model")
    .agg(
        pl.sum("Quantity").alias("Total_Quantity_Sold"),
        pl.mean("Sale_Price").alias("Avg_Sale_Price"),
        pl.len().alias("Transaction_Count"),
    )
    .sort("Model")
)

# Convert to pandas for easier plotting with Plotly GO
model_sales_summary_pd = model_sales_summary.to_pandas()


# --- 2. Create the 3-Chart Layout ---
fig = make_subplots(
    rows=1,
    cols=3,
    subplot_titles=(
        "<b>Top 15 Models by Quantity Sold</b>",
        "<b>Correlation: Quantity Sold vs. Average Price</b>",
        "<b>Top 15 Models by Average Price</b>",
    ),
    column_widths=[0.28, 0.44, 0.28],  # Give center plot more space
)


# --- 3. Left Chart: Top Models by Quantity Sold ---
top_quantity = model_sales_summary_pd.sort_values(
    "Total_Quantity_Sold", ascending=False
).head(15)
fig.add_trace(
    go.Bar(
        x=top_quantity["Model"],
        y=top_quantity["Total_Quantity_Sold"],
        marker_color=COLORS[1],
        name="Quantity Sold",
    ),
    row=1,
    col=1,
)


# --- 4. Middle Chart: Correlation Scatter Plot ---
fig.add_trace(
    go.Scatter(
        x=model_sales_summary_pd["Total_Quantity_Sold"],
        y=model_sales_summary_pd["Avg_Sale_Price"],
        mode="markers",
        text=model_sales_summary_pd["Model"],  # Text for hover
        hovertemplate=(
            "<b>%{text}</b><br><br>"
            + "Total Units Sold: %{x:,}<br>"
            + "Average Sale Price: $%{y:,.2f}"
            + "<extra></extra>"  # Hides the trace name on hover
        ),
        marker=dict(color=COLORS[0], size=8, opacity=0.7),
    ),
    row=1,
    col=2,
)


# --- 5. Right Chart: Top Models by Average Price ---
top_price = model_sales_summary_pd.sort_values("Avg_Sale_Price", ascending=False).head(
    15
)
fig.add_trace(
    go.Bar(
        x=top_price["Model"],
        y=top_price["Avg_Sale_Price"],
        marker_color=COLORS[2],
        name="Average Price",
    ),
    row=1,
    col=3,
)


# --- 6. Final Layout Updates ---
fig.update_layout(
    title_text="<b>Analysis of Sales Volume vs. Average Price by Car Model</b>",
    height=600,
    showlegend=False,
    template="plotly_white",
    bargap=0.2,
)

# Update axis titles for clarity
fig.update_yaxes(title_text="Total Units Sold", row=1, col=1)
fig.update_xaxes(title_text="Car Model", tickangle=-45, row=1, col=1)

fig.update_xaxes(title_text="Total Units Sold", row=1, col=2)
fig.update_yaxes(title_text="Average Sale Price ($)", row=1, col=2)

fig.update_yaxes(title_text="Average Sale Price ($)", row=1, col=3)
fig.update_xaxes(title_text="Car Model", tickangle=-45, row=1, col=3)

fig.show()

In [21]:
# Sales Volume by Region
sales_by_region = (
    df_master.group_by("Region")
    .agg(
        pl.sum("Quantity").alias("Total_Quantity"),
        pl.sum("Sale_Price").alias("Total_Revenue"),
    )
    .sort("Total_Revenue", descending=True)
)

fig = px.bar(
    sales_by_region.to_pandas(),
    x="Region",
    y="Total_Revenue",
    title="🗺️ Total Revenue by Region",
    color="Region",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False, yaxis_title="Total Revenue ($)")
fig.show()

In [22]:
# Sales by Payment Method
sales_by_payment = (
    df_master.group_by("Payment_Method")
    .agg(
        pl.sum("Sale_Price").alias("Total_Revenue"),
        pl.len().alias("Transaction_Count"),
    )
    .sort("Total_Revenue", descending=True)
)

fig = px.bar(
    sales_by_payment.to_pandas(),
    x="Payment_Method",
    y="Total_Revenue",
    title="💳 Total Revenue by Payment Method",
    color="Payment_Method",
    color_discrete_sequence=COLORS,
)
fig.update_layout(showlegend=False, yaxis_title="Total Revenue ($)")
fig.show()

In [23]:
# Top 10 Salespersons by Revenue
top_salespersons = (
    df_master.group_by("Salesperson")
    .agg(pl.sum("Sale_Price").alias("Total_Revenue"), pl.len().alias("Deals_Closed"))
    .sort("Total_Revenue", descending=True)
    .head(10)
)

fig = px.bar(
    top_salespersons.to_pandas(),
    x="Salesperson",
    y="Total_Revenue",
    title="🏆 Top 10 Salespersons by Revenue",
    color="Salesperson",
    color_discrete_sequence=COLORS,
)
fig.update_layout(
    showlegend=False, yaxis_title="Total Revenue ($)", xaxis_tickangle=-45
)
fig.show()

#### 4.2.3 Scatter Plot Matrix

In [24]:
# Scatter matrix for key numerical features
scatter_cols = ["Price", "Year", "Sale_Price", "Quantity", "Age"]
scatter_cols = [col for col in scatter_cols if col in df_master.columns]

fig = px.scatter_matrix(
    df_master.select(scatter_cols).sample(n=min(1000, df_master.shape[0])).to_pandas(),
    dimensions=scatter_cols,
    title="🔍 Scatter Plot Matrix",
    color_discrete_sequence=[COLORS[0]],
)
fig.update_traces(diagonal_visible=False)
fig.update_layout(height=800)
fig.show()

---
### 4.3 Temporal Analysis (Time-Series)

In [25]:
# Parse Sale_Date to date type
df_master = df_master.with_columns(
    pl.col("Sale_Date").str.to_date().alias("Sale_Date_Parsed")
)

# Extract Month and Day of Week
df_master = df_master.with_columns(
    [
        pl.col("Sale_Date_Parsed").dt.month().alias("Month"),
        pl.col("Sale_Date_Parsed").dt.weekday().alias("DayOfWeek"),
        pl.col("Sale_Date_Parsed").dt.year().alias("Sale_Year"),
    ]
)

print("✅ Date features extracted!")

✅ Date features extracted!

In [26]:
# Monthly Sales Trend
monthly_sales = (
    df_master.group_by(["Sale_Year", "Month"])
    .agg(
        pl.sum("Sale_Price").alias("Total_Revenue"),
        pl.len().alias("Transaction_Count"),
    )
    .sort(["Sale_Year", "Month"])
)

# Create a combined date column for plotting
monthly_sales = monthly_sales.with_columns(
    (
        pl.col("Sale_Year").cast(str) + "-" + pl.col("Month").cast(str).str.zfill(2)
    ).alias("Year_Month")
)

fig = px.line(
    monthly_sales.to_pandas(),
    x="Year_Month",
    y="Total_Revenue",
    title="📈 Monthly Revenue Trend",
    markers=True,
    color_discrete_sequence=[COLORS[0]],
)
fig.update_layout(
    xaxis_title="Month", yaxis_title="Total Revenue ($)", xaxis_tickangle=-45
)
fig.show()

In [27]:
# Sales by Month (Seasonality)
month_names = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]

seasonality = (
    df_master.group_by("Month")
    .agg(
        pl.sum("Sale_Price").alias("Total_Revenue"),
        pl.len().alias("Transaction_Count"),
    )
    .sort("Month")
)

seasonality_pd = seasonality.to_pandas()
seasonality_pd["Month_Name"] = seasonality_pd["Month"].apply(
    lambda x: month_names[x - 1] if 1 <= x <= 12 else "Unknown"
)

fig = px.bar(
    seasonality_pd,
    x="Month_Name",
    y="Total_Revenue",
    title="📆 Seasonality: Revenue by Month",
    color="Total_Revenue",
    color_continuous_scale="Blues",
)
fig.update_layout(xaxis_title="Month", yaxis_title="Total Revenue ($)")
fig.show()

In [28]:
# Sales by Day of Week
day_names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

dow_sales = (
    df_master.group_by("DayOfWeek")
    .agg(
        pl.sum("Sale_Price").alias("Total_Revenue"),
        pl.len().alias("Transaction_Count"),
    )
    .sort("DayOfWeek")
)

dow_pd = dow_sales.to_pandas()
dow_pd["Day_Name"] = dow_pd["DayOfWeek"].apply(
    lambda x: day_names[x] if 0 <= x <= 6 else "Unknown"
)

fig = px.bar(
    dow_pd,
    x="Day_Name",
    y="Total_Revenue",
    title="📅 Sales by Day of Week",
    color="Total_Revenue",
    color_continuous_scale="Greens",
)
fig.update_layout(xaxis_title="Day of Week", yaxis_title="Total Revenue ($)")
fig.show()

---
### 4.4 Data Integrity Check

In [29]:
# Data Shape Verification
print("=== Data Shape Verification ===")
print(f"Original Sales rows: {df_sales.shape[0]:,}")
print(f"Master Dataset rows: {df_master.shape[0]:,}")
print(f"Difference: {df_sales.shape[0] - df_master.shape[0]:,} rows")

if df_sales.shape[0] == df_master.shape[0]:
    print("\n✅ No data loss during merge!")
else:
    print("\n⚠️ Some rows may have been lost during merge. Check for missing IDs.")

=== Data Shape Verification ===
Original Sales rows: 49,988
Master Dataset rows: 49,988
Difference: 0 rows

✅ No data loss during merge!

In [30]:
# Cross-Table Consistency: Check for Car_IDs in Sales not in Cars
sales_car_ids = set(df_sales["Car_ID"].to_list())
cars_car_ids = set(df_cars["Car_ID"].to_list())

missing_cars = sales_car_ids - cars_car_ids

print("=== Car_ID Integrity Check ===")
print(f"Unique Car_IDs in Sales: {len(sales_car_ids):,}")
print(f"Unique Car_IDs in Cars: {len(cars_car_ids):,}")
print(f"Car_IDs in Sales but not in Cars: {len(missing_cars):,}")

if len(missing_cars) == 0:
    print("\n✅ All Car_IDs in Sales exist in Cars table!")
else:
    print(f"\n⚠️ {len(missing_cars)} Car_IDs in Sales are not in Cars table:")
    print(list(missing_cars)[:10])  # Show first 10

=== Car_ID Integrity Check ===
Unique Car_IDs in Sales: 49,489
Unique Car_IDs in Cars: 49,489
Car_IDs in Sales but not in Cars: 0

✅ All Car_IDs in Sales exist in Cars table!

In [31]:
# Cross-Table Consistency: Check for Customer_IDs in Sales not in Customers
sales_customer_ids = set(df_sales["Customer_ID"].to_list())
customers_customer_ids = set(df_customers["Customer_ID"].to_list())

missing_customers = sales_customer_ids - customers_customer_ids

print("=== Customer_ID Integrity Check ===")
print(f"Unique Customer_IDs in Sales: {len(sales_customer_ids):,}")
print(f"Unique Customer_IDs in Customers: {len(customers_customer_ids):,}")
print(f"Customer_IDs in Sales but not in Customers: {len(missing_customers):,}")

if len(missing_customers) == 0:
    print("\n✅ All Customer_IDs in Sales exist in Customers table!")
else:
    print(
        f"\n⚠️ {len(missing_customers)} Customer_IDs in Sales are not in Customers table:"
    )
    print(list(missing_customers)[:10])  # Show first 10

=== Customer_ID Integrity Check ===
Unique Customer_IDs in Sales: 500
Unique Customer_IDs in Customers: 500
Customer_IDs in Sales but not in Customers: 0

✅ All Customer_IDs in Sales exist in Customers table!

In [ ]:
# Save merged dataset to cleaned folder using helper function
merged_path = save_to("cleaned", "Sales_merged.csv")
if os.getenv("ALLOW_DATA_WRITE") == "1":
    df_master.write_csv(merged_path)
    print(f"✅ Merged dataset saved to: {merged_path}")
else:
    print(f"⚠️ Skipping write to {merged_path} (protected). To enable set ALLOW_DATA_WRITE=1.")
print(f"   Shape: {df_master.shape[0]:,} rows × {df_master.shape[1]} columns")

✅ Merged dataset saved to: /home/ccyod/Clone/aomsin-tid-data/data/cleaned/Sales_merged.csv
   Shape: 49,988 rows × 31 columns

## 5. Dashboard Data Export
Saving metrics and charts for the Aomsin Tid Data Dashboard.

In [33]:
# --- Publish Highlights to Dashboard ---
total_revenue = df_master["Sale_Price"].sum()
total_units = df_master.shape[0]
avg_price = df_master["Sale_Price"].mean()
top_region = (
    df_master.group_by("Region")
    .agg(pl.sum("Sale_Price"))
    .sort("Sale_Price", descending=True)["Region"][0]
)

summary_data = {
    "project_info": {
        "title": "Aomsin Tid Data Dashboard",
        "description": "This project provides comprehensive intelligence on the automotive market, analyzing trends, pricing models, and inventory distribution. Leveraging the Raw Car Sales Data Set (sourced from Kaggle), we employ machine learning models to predict market values and identify key economic indicators.",
        "dataset_name": "Raw Car Sales Data Set",
        "dataset_source_link": "https://www.kaggle.com/datasets/yukeshgk/raw-car-sales-data-set?select=Sales.csv",
        "dataset_files": "Cars.csv, Customers.csv, Sales.csv",
        "dataset_columns": "Car_ID, Brand, Model, Year, Color, Engine_Type, Transmission, Price, Quantity_In_Stock, Status",
    },
    "metrics": {
        "total_revenue": round(total_revenue, 2),
        "total_units": total_units,
        "average_price": round(avg_price, 2),
        "top_performing_region": top_region,
    },
    "last_updated": "2026-02-07",
}

save_result(summary_data, "overview_summary", topic="general")

✅ [GENERAL] Data saved to: /home/ccyod/Clone/aomsin-tid-data/data/general/overview_summary.toml

In [34]:
# --- Generate Dynamic Charts for Dashboard (UPDATED with size & variant) ---
charts_list = []

# 1. Line Chart: Price Trend (Yearly) - Full Width
yearly_trend = (
    df_cars.group_by("Year").agg(pl.col("Price").mean().alias("avg_price")).sort("Year")
)

c1 = ChartConfig(
    title="Average Price per Year",
    chart_type="line",
    description="Historical pricing trends showing market evolution",
    x_axis_key="Year",
    x_axis_label="Year",
    y_axis_unit="$",
    size="full",  # Full width chart
    variant="primary"  # Use primary pink variant
)
c1.add_series("avg_price", "Average Price", variant="chart-1")
c1.set_data(yearly_trend.to_dicts())
charts_list.append(c1.config)

# 2. Pie Chart: Engine Distribution - Half Width
engine_dist = (
    df_cars.group_by("Engine_Type")
    .agg(pl.len().alias("value"))
    .sort("value", descending=True)
)

c2 = ChartConfig(
    title="Engine Type Distribution",
    chart_type="pie",
    description="Market share by engine technology",
    x_axis_key="Engine_Type",
    size="half"  # Half width (default)
)
c2.add_series("value", "Count", variant="blue")
c2.set_data(engine_dist.to_dicts())
charts_list.append(c2.config)

# 3. Stacked Bar: Revenue vs Costs (Simulated) by Top 5 Models - Half Width
model_financials = (
    df_master.group_by("Model")
    .agg(pl.sum("Sale_Price").alias("Revenue"))
    .sort("Revenue", descending=True)
    .head(5)
)
model_financials = model_financials.with_columns(
    (pl.col("Revenue") * 0.7).alias("Cost"), (pl.col("Revenue") * 0.3).alias("Profit")
)

c3 = ChartConfig(
    title="Top 5 Models Financials (Stacked)",
    chart_type="bar",
    description="Revenue breakdown into Cost and Profit",
    x_axis_key="Model",
    y_axis_unit="$",
    size="half",
    variant="success"
)
c3.add_series("Cost", "Estimated Cost", variant="yellow", stack_id="a")
c3.add_series("Profit", "Net Profit", variant="green", stack_id="a")
c3.set_data(model_financials.to_dicts())
charts_list.append(c3.config)

# 4. Radar Chart: Top 3 Brands Comparison - Half Width
top_3_brands = brand_counts.head(3)["Brand"].to_list()
radar_metrics = (
    df_master.filter(pl.col("Brand").is_in(top_3_brands))
    .group_by("Brand")
    .agg(
        pl.col("Price").mean().alias("Price"),
        pl.col("Age").mean().alias("Buyer_Age"),
        pl.len().alias("Volume"),
    )
)

# Normalize metrics for Radar (0-100 scale)
def normalize(s):
    return (s - s.min()) / (s.max() - s.min()) * 100

radar_df = radar_metrics.with_columns(
    normalize(pl.col("Price")).alias("Price_Score"),
    normalize(pl.col("Buyer_Age")).alias("Age_Score"),
    normalize(pl.col("Volume")).alias("Volume_Score"),
)

# Pivot to: metric, brand_a, brand_b, brand_c
radar_data = [
    {
        "metric": "Price",
        top_3_brands[0]: radar_df.filter(pl.col("Brand") == top_3_brands[0])[
            "Price_Score"
        ][0],
        top_3_brands[1]: radar_df.filter(pl.col("Brand") == top_3_brands[1])[
            "Price_Score"
        ][0],
        top_3_brands[2]: radar_df.filter(pl.col("Brand") == top_3_brands[2])[
            "Price_Score"
        ][0],
    },
    {
        "metric": "Buyer Age",
        top_3_brands[0]: radar_df.filter(pl.col("Brand") == top_3_brands[0])[
            "Age_Score"
        ][0],
        top_3_brands[1]: radar_df.filter(pl.col("Brand") == top_3_brands[1])[
            "Age_Score"
        ][0],
        top_3_brands[2]: radar_df.filter(pl.col("Brand") == top_3_brands[2])[
            "Age_Score"
        ][0],
    },
    {
        "metric": "Volume",
        top_3_brands[0]: radar_df.filter(pl.col("Brand") == top_3_brands[0])[
            "Volume_Score"
        ][0],
        top_3_brands[1]: radar_df.filter(pl.col("Brand") == top_3_brands[1])[
            "Volume_Score"
        ][0],
        top_3_brands[2]: radar_df.filter(pl.col("Brand") == top_3_brands[2])[
            "Volume_Score"
        ][0],
    },
]

c4 = ChartConfig(
    title="Top 3 Brands Comparison (Normalized)",
    chart_type="radar",
    description="Relative scoring of Price, Buyer Age, and Volume",
    x_axis_key="metric",
    size="half"
)
# Use different color variants for each brand
c4.add_series(top_3_brands[0], top_3_brands[0], variant="pink")
c4.add_series(top_3_brands[1], top_3_brands[1], variant="mauve")
c4.add_series(top_3_brands[2], top_3_brands[2], variant="blue")
c4.set_data(radar_data)
charts_list.append(c4.config)

# 5. Composed Chart: Revenue vs Transaction Count (Monthly) - Full Width
monthly_chart_data = monthly_sales.to_dicts()

c5 = ChartConfig(
    title="Revenue vs Transaction Volume (Monthly)",
    chart_type="composed",
    description="Tracking revenue alongside number of deals closed",
    x_axis_key="Year_Month",
    y_axis_unit="$",
    size="full",  # Full width for better readability
    variant="info"
)
c5.add_series("Total_Revenue", "Revenue", variant="peach", type="bar")
c5.add_series("Transaction_Count", "Deals Count", variant="sky", type="line")
c5.set_data(monthly_chart_data)
charts_list.append(c5.config)

# Save Overview Charts for general/overview page
save_result({"charts": charts_list}, "overview_charts", topic="general")
print(f"✅ Generated {len(charts_list)} charts with size & variant for the dashboard!")
print("   Using Catppuccin Mocha Pink color variants: pink, mauve, blue, green, peach, yellow, sky")

✅ [GENERAL] Data saved to: /home/ccyod/Clone/aomsin-tid-data/data/general/overview_charts.toml
✅ Generated 5 charts with size & variant for the dashboard!
   Using Catppuccin Mocha Pink color variants: pink, mauve, blue, green, peach, yellow, sky

In [35]:
# --- Generate Analysis Page Charts ---
analysis_charts = []

# 1. Regional Performance - Full Width
regional_data = (
    df_master.group_by("Region")
    .agg(
        pl.sum("Sale_Price").alias("Revenue"),
        pl.len().alias("Transactions"),
        pl.mean("Sale_Price").alias("Avg_Price")
    )
    .sort("Revenue", descending=True)
    .to_dicts()
)

c1 = ChartConfig(
    title="Revenue by Region",
    chart_type="bar",
    description="Total revenue and transaction volume across regions",
    x_axis_key="Region",
    y_axis_unit="$",
    size="full",
    variant="primary"
)
c1.add_series("Revenue", "Total Revenue", variant="pink")
c1.add_series("Avg_Price", "Average Price", variant="mauve")
c1.set_data(regional_data)
analysis_charts.append(c1.config)

# 2. Monthly Revenue Trend - Full Width
c2 = ChartConfig(
    title="Monthly Revenue Trend",
    chart_type="line",
    description="Sales revenue over time showing seasonal patterns",
    x_axis_key="Year_Month",
    y_axis_unit="$",
    size="full",
    variant="info"
)
c2.add_series("Total_Revenue", "Revenue", variant="blue")
c2.set_data(monthly_sales.to_dicts())
analysis_charts.append(c2.config)

# 3. Top 10 Models by Revenue - Half Width
top_models = (
    df_master.group_by("Model")
    .agg(pl.sum("Sale_Price").alias("Revenue"))
    .sort("Revenue", descending=True)
    .head(10)
    .to_dicts()
)

c3 = ChartConfig(
    title="Top 10 Models by Revenue",
    chart_type="bar",
    description="Best performing car models by total sales revenue",
    x_axis_key="Model",
    y_axis_unit="$",
    size="half",
    variant="success"
)
c3.add_series("Revenue", "Total Revenue", variant="green")
c3.set_data(top_models)
analysis_charts.append(c3.config)

# 4. Payment Method Distribution - Half Width
payment_data = (
    df_master.group_by("Payment_Method")
    .agg(
        pl.sum("Sale_Price").alias("Revenue"),
        pl.len().alias("Count")
    )
    .to_dicts()
)

c4 = ChartConfig(
    title="Payment Method Distribution",
    chart_type="pie",
    description="Revenue breakdown by payment method",
    x_axis_key="Payment_Method",
    size="half"
)
c4.add_series("Revenue", "Revenue", variant="chart-1")
c4.set_data(payment_data)
analysis_charts.append(c4.config)

# 5. Seasonality Analysis - Full Width
seasonality_data = seasonality.to_dicts()

c5 = ChartConfig(
    title="Seasonal Revenue Patterns",
    chart_type="bar",
    description="Monthly revenue distribution showing seasonal trends",
    x_axis_key="Month_Name",
    y_axis_unit="$",
    size="full",
    variant="warning"
)
c5.add_series("Total_Revenue", "Revenue", variant="peach")
c5.set_data(seasonality_data)
analysis_charts.append(c5.config)

# 6. Day of Week Analysis - Half Width
dow_data = dow_pd.to_dict('records')

c6 = ChartConfig(
    title="Sales by Day of Week",
    chart_type="bar",
    description="Revenue distribution across weekdays",
    x_axis_key="Day_Name",
    y_axis_unit="$",
    size="half"
)
c6.add_series("Total_Revenue", "Revenue", variant="teal")
c6.set_data(dow_data)
analysis_charts.append(c6.config)

# 7. Top Brands Revenue - Half Width
brand_revenue = (
    df_master.group_by("Brand")
    .agg(pl.sum("Sale_Price").alias("Revenue"))
    .sort("Revenue", descending=True)
    .head(10)
    .to_dicts()
)

c7 = ChartConfig(
    title="Top 10 Brands by Revenue",
    chart_type="bar",
    description="Leading car brands by total sales revenue",
    x_axis_key="Brand",
    y_axis_unit="$",
    size="half",
    variant="secondary"
)
c7.add_series("Revenue", "Total Revenue", variant="mauve")
c7.set_data(brand_revenue)
analysis_charts.append(c7.config)

# Save all analysis charts
save_result({"charts": analysis_charts}, "analysis_charts", topic="analysis")
print(f"✅ Generated {len(analysis_charts)} charts for the Analysis page!")
print("   Charts saved to data/analysis/ for the /analysis dashboard page")

✅ [ANALYSIS] Data saved to: /home/ccyod/Clone/aomsin-tid-data/data/analysis/analysis_charts.toml
✅ Generated 7 charts for the Analysis page!
   Charts saved to data/analysis/ for the /analysis dashboard page